# Generated by Django 2.1.5 on 2021-03-25 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 16, 39, 52, 653603), verbose_name='date published'),
        ),
    ]
