# Generated by Django 2.1.5 on 2021-03-25 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210325_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 16, 40, 8, 136590), verbose_name='date published'),
        ),
    ]
