# Generated by Django 2.1.5 on 2021-03-25 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210325_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 16, 50, 45, 393893), verbose_name='date published'),
        ),
    ]
